### ISSUE TITLE
Local development steps are repeated in `Readme.md`

### ISSUE THREAD

**Issue by v-jiaodi** [pamelafox/flask-charts-api-container-app#6]
**Describe the issue:**

Section [link](https://github.com/pamelafox/flask-charts-api-container-app#local-development): Repeat steps

![image](https://user-images.githubusercontent.com/80496810/224620025-1ca679f6-7515-4dff-83f4-a55faa54d238.png)

**Suggestion:**
Remove duplicate steps

@pamelafox  for notification.

**Comment by pamelafox** [comment]
Fixed, thanks!
